trigger:
  branches:
    include:
    - master
  tags:
    include:
    - "*"

stages:
  - stage: CI
    variables:
      TILEDB_VERSION: erica/ch922/windows-build
      MARIADB_VERSION: 'mariadb-10.5.0'
      ROOT_DIR: '$(Build.Repository.Localpath)\'
      BUILD_DEPS: '$(Build.Repository.Localpath)\build_deps'
      TILEDB_SRC: '$(Build.Repository.Localpath)\tiledb_src'
      TILEDB_INSTALL: '$(Build.Repository.Localpath)\tiledb_install'
    condition: not(or(startsWith(variables['Build.SourceBranch'], 'refs/tags'), contains(variables['Build.SourceBranchName'], 'release-')))
    jobs:
#    - job: Build
#      strategy:
#        matrix:
#          linux:
#            imageName: 'ubuntu-16.04'
#            CXX: g++
#          macOS:
#            imageName: 'macOS-10.14'
#            CXX: clang++
#
#      pool:
#        vmImage: $(imageName)
#      steps:
#      - template: scripts/azure-linux_mac.yml

    - job: Build_windows
      strategy:
        matrix:
          VS2019:
            imageName: 'windows-2019'
      pool:
        vmImage: $(imageName)
      steps:
      - template: scripts/azure-windows.yml

  - stage: Docker
    condition: or(startsWith(variables['Build.SourceBranch'], 'refs/tags'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
    - job: Docker
      pool:
        vmImage: 'ubuntu-18.04'

      strategy:
        matrix:
          tiledb-mariadb:
            dockerfile: docker/Dockerfile
            repository: tiledb/tiledb-mariadb
            context: .
          tiledb-mariadb-server:
            dockerfile: docker/Dockerfile
            repository: tiledb/tiledb-mariadb-server
            context: .

      steps:
      - template: scripts/build-images.yml
